---
name: Publish Packages

on:
  release:
    types: [published]

jobs:
  build:
    name: Publish Packages

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      # attestations: write
      # id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm run publish:packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
